# -*- coding: utf-8 -*-
"""regresi-linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lgh0p4feJ-r_pQuSoXOIXNJkdWsDPjgG
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Dataset
X = np.array([5, 4, 6, 5, 5, 5, 6, 6, 2, 7, 7]).reshape(-1, 1)
y = np.array([85, 103, 70, 82, 89, 98, 66, 95, 169, 70, 48])

# Membuat model regresi linear
model = LinearRegression()
model.fit(X, y)

# Menampilkan hasil
intercept = model.intercept_
slope = model.coef_[0]
print(f"Persamaan regresi: y = {slope:.2f}x + {intercept:.2f}")

# Prediksi nilai y berdasarkan X
y_pred = model.predict(X)

# Evaluasi model
mse = mean_squared_error(y, y_pred)
r2 = r2_score(y, y_pred)
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

# Visualisasi data dan regresi
plt.scatter(X, y, color='blue', label='Data Sebenarnya')
plt.plot(X, y_pred, color='red', label='Model Regresi')
plt.xlabel('Usia Mobil (tahun)')
plt.ylabel('Harga Mobil ($100)')
plt.title('Regresi Linear: Usia Mobil vs Harga Mobil')
plt.legend()
plt.grid(True)
plt.show()